spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homeloan
    username: loanuser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update    # automatically create/update tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: my-secret-key
